# Simple RNN
출처: https://excelsior-cjh.tistory.com/183

In [1]:
import numpy as np
import tensorflow as tf

n_inputs = 3 
n_neurons = 5 
X0 = tf.placeholder(tf.float32, [None, n_inputs]) 
X1 = tf.placeholder(tf.float32, [None, n_inputs]) 

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32)) 
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32)) 
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32)) 

Y0 = tf.tanh(tf.matmul(X0, Wx) + b) 
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

# input data (mini-batch) 
#t = 0
X0_batch = np.array([[0, 1, 2], # sample 0 
                     [3, 4, 5], # sample 1 
                     [6, 7, 8], # sample 2 
                     [9, 0, 1]]) # sample 3 
#t = 1 
X1_batch = np.array([[9, 8, 7], [3, 4, 5], [6, 5, 4], [3, 2, 1]]) 

with tf.Session() as sess: 
    tf.global_variables_initializer().run() 
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch}) 
    print('Y0_val:{}\n{}'.format(Y0_val.shape, Y0_val))
    print('Y1_val:{}\n{}'.format(Y1_val.shape, Y1_val))

Y0_val:(4, 5)
[[-0.99945116 -0.4396      0.53413403 -0.9987171  -0.11120202]
 [-1.         -0.8893854   0.9998925  -0.99999994  0.76220447]
 [-1.         -0.9825437   1.         -1.          0.9712885 ]
 [-1.         -0.19585446  0.9999999   0.80428195  0.09622727]]
Y1_val:(4, 5)
[[-1.         -0.99673605  1.         -1.          0.98843205]
 [-1.         -0.7941649   0.99999946 -0.9999999   0.6598104 ]
 [-1.         -0.6553332   1.         -0.9999832   0.9800722 ]
 [-1.         -0.53250164  0.99997544 -0.9626149   0.877505  ]]
