In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([3,4,5])
a @ b.T

26

In [4]:
a.shape

(3,)

In [6]:
(b.T).shape

(3,)

In [8]:
np.expand_dims(a, -1)

array([[1],
       [2],
       [3]])

In [15]:
np.expand_dims(a, 0)

array([[1, 2, 3]])

In [19]:
np.expand_dims(a, 1).shape

(3, 1)

In [18]:
np.expand_dims(a, 1) @ np.expand_dims(b, 0)

array([[ 3,  4,  5],
       [ 6,  8, 10],
       [ 9, 12, 15]])

In [21]:
a @ np.expand_dims(b, 0)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)

np.dot

In [22]:
np.dot(a, b)

26

In [23]:
np.dot(a, np.expand_dims(b, 0))

ValueError: shapes (3,) and (1,3) not aligned: 3 (dim 0) != 1 (dim 0)

In [24]:
c = [[1,2,3],[4,5,6],[7,8,9]]

In [25]:
c @ a

array([14, 32, 50])

In [27]:
(c @ a).shape

(3,)

In [29]:
a * b

array([ 3,  8, 15])

np.choose

In [33]:
input_array = np.array([[ 3, 14],
       [12,  5],
       [75, 50]])

In [34]:
select_id = [0, 1, 1]

In [35]:
output_array = np.choose(select_id, input_array.T)

In [36]:
output_array

array([ 3,  5, 50])