# Simple RNN
출처: https://excelsior-cjh.tistory.com/183

In [2]:
import numpy as np
import tensorflow as tf

n_inputs = 3 
n_neurons = 5 
X0 = tf.placeholder(tf.float32, [None, n_inputs]) 
X1 = tf.placeholder(tf.float32, [None, n_inputs]) 

Wx = tf.Variable(tf.random_normal(shape=[n_inputs, n_neurons], dtype=tf.float32)) 
Wy = tf.Variable(tf.random_normal(shape=[n_neurons, n_neurons], dtype=tf.float32)) 
b = tf.Variable(tf.zeros([1, n_neurons], dtype=tf.float32)) 

Y0 = tf.tanh(tf.matmul(X0, Wx) + b) 
Y1 = tf.tanh(tf.matmul(Y0, Wy) + tf.matmul(X1, Wx) + b)

# input data (mini-batch) 
#t = 0
X0_batch = np.array([[0, 1, 2], # sample 0 
                     [3, 4, 5], # sample 1 
                     [6, 7, 8], # sample 2 
                     [9, 0, 1]]) # sample 3 
#t = 1 
X1_batch = np.array([[9, 8, 7], [3, 4, 5], [6, 5, 4], [3, 2, 1]]) 

with tf.Session() as sess: 
    tf.global_variables_initializer().run() 
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch}) 
    print('Y0_val:{}\n{}'.format(Y0_val.shape, Y0_val))
    print('Y1_val:{}\n{}'.format(Y1_val.shape, Y1_val))

Y0_val:(4, 5)
[[-0.9346479  -0.999754   -0.9352834  -0.19293833 -0.5301121 ]
 [-0.9996704  -1.         -0.95082015 -0.68673545  0.8658863 ]
 [-0.9999984  -1.         -0.9626988  -0.9029772   0.99683195]
 [ 0.41489333 -0.9999999   0.9999999  -0.7730039   0.9999999 ]]
Y1_val:(4, 5)
[[-0.9999997  -1.          0.98264104 -0.7184118   0.99999994]
 [-0.99953645 -1.         -0.5782614   0.78892785  0.9998648 ]
 [-0.9972815  -1.          0.9901008   0.75327677  0.9999999 ]
 [ 0.93395495 -0.9999841   0.9802242   0.99958     0.99152684]]
