# PyTorch가 무엇인가요?
공식 Tutorial https://tutorials.pytorch.kr/beginner/blitz/tensor_tutorial.html  
Torch API https://pytorch.org/docs/stable/torch.html  
블로그 정리 https://zzsza.github.io/data/2018/02/03/pytorch-1/

In [13]:
import torch

Tensor

In [40]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

# Tensor의 속성 재사용
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 메소드는 크기를 받습니다
print(x)

x = torch.randn_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 합니다!
print(x)                                      # 결과는 동일한 크기를 갖습니다

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8669,  0.2017,  1.6530],
        [-0.2304,  0.7288, -0.2216],
        [-0.4809, -0.3004,  0.6888],
        [ 0.4748, -0.9201,  0.7242],
        [ 0.3102,  0.0844,  1.2195]])


In [41]:
data1 = torch.Tensor([[1,2,3,4]
                    ,[4,5,6,7]
                    ,[7,8,9,10]])

In [27]:
# size
data1.size

<function Tensor.size>

In [28]:
data1.size(0)

3

view: reshape

In [32]:
# -1은 다른 차원을 통해 유추
data1.view(3, -1) 

tensor([[ 1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.],
        [ 7.,  8.,  9., 10.]])

In [33]:
data1.view(-1, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  4.,  5.],
        [ 6.,  7.,  7.],
        [ 8.,  9., 10.]])

In [35]:
data1.view(12)

tensor([ 1.,  2.,  3.,  4.,  4.,  5.,  6.,  7.,  7.,  8.,  9., 10.])

narrow
* narrow(input, dim, start, length)
* dim is input from start to start + length
* start 부터 length 만큼 떨어진 데이터를 반환

In [36]:
bsz = 2
nbatch = data1.size(0) // bsz
data1.narrow(0, 0, nbatch * bsz)

tensor([[1., 2., 3., 4.],
        [4., 5., 6., 7.]])

expand: 차원 늘이기

In [47]:
y = torch.tensor([[1], [2], [3]])

In [48]:
y.expand(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [49]:
y.expand(-1, 4)   # -1 means not changing the size of that dimension

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])